title: Alice au pays des cryptos

deployment:
  targets:
    - name: "production"
      URL: "s3://9336cf5b1949519492a4da6f2ab0244a9dfebba6cf35f74d7a4b3fb348908235?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage"

